# Generated by Django 5.1.7 on 2025-03-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('bio', models.TextField()),
                ('long_bio', models.TextField()),
                ('years_of_experience', models.CharField(max_length=200)),
                ('completed_projects', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=200)),
                ('happy_clients', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('cv', models.FileField(upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='TechnichalExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('percent', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('front-end', 'Front-End'), ('back-end', 'Back-End')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='technology/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project/')),
                ('live_link', models.CharField(max_length=200)),
                ('github_link', models.CharField(max_length=200)),
                ('technology', models.ManyToManyField(to='home.technology')),
            ],
        ),
    ]
