# Generated by Django 5.1.7 on 2025-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='icon',
        ),
        migrations.AddField(
            model_name='technology',
            name='icon_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
