# Generated by Django 5.1.7 on 2025-03-14 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_criteria_projectdetail_delete_projectstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='key_features',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='project_overview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='criteria',
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='criteria',
            field=models.ManyToManyField(related_name='project_details', to='home.criteria'),
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.technology')),
            ],
            options={
                'unique_together': {('project', 'technology')},
            },
        ),
    ]
