# Generated by Django 5.1.7 on 2025-03-16 18:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_criteria_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='key_features',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_overview',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
