# Generated by Django 5.1.7 on 2025-03-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_projectdetail_key_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='PojTechnology',
            field=models.ManyToManyField(related_name='project_technologies', to='home.technology'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='diagram_file',
            field=models.FileField(default='', upload_to='diagram/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DevelopmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('week', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='home.projectdetail')),
            ],
        ),
    ]
