# Generated by Django 5.1.7 on 2025-03-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='what_ilearned',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
